[directories]
spec_dir = /data2/eortiz/spectra
; spec_dir = /home/elom/phd/code/spectra
raw_data_dir = ${spec_dir}/raw/flux_wave_ivar_raw
output = ${spec_dir}

[files]
spectra_df = 0_01_z_0_5_4_0_snr_inf.csv.gz

[grid]
number_waves = 4000
lower = 3500
upper = 7500

[parameters]
processes = 48
number_spectra = -1
